
database:
    sample1:
        description: 'For the pilot experiment a group of 10 pigeons (columba livia domestica) is recruited. Subjects are experimentally naive and food deprived to 80% free ranging weight'
        species: 'columba livia domestica'
        subjects:
            subject1:
                id: 'P007'
                sex: 'male'
                age: '2019'
                features: 'dark head with light stripes on the wings'
                group:
                
            subject2:
                id: 
                sex: 
                age: 
                features: 
                group:
                
            subject3:
                id: 
                sex: 
                age: 
                features: 
                group:
                
            subject4:
                id: 
                sex: 
                age: 
                features: 
                group:

