
RPi4Toolbox: 
    path: '/home/hidalggc/Documents/RPi4Toolbox'
hardware:
    path: '/home/hidalggc/Documents/RPi4Toolbox/GUI/Toolbox/hardware.yaml'
experiment:
    path: '/home/hidalggc/Documents/RPi4Toolbox/GUI/Toolbox/experiment.yaml'
database:
    path: '/home/hidalggc/Documents/RPi4Toolbox/GUI/Toolbox/database.yaml'
metadata:
    path: '/home/hidalggc/Documents/RPi4Toolbox/GUI/Toolbox/metadata.yaml'

